### ISSUE TITLE
Namespace collisions issue

### ISSUE THREAD

**Issue by volodymyrdovhan** [cgrevisse/moodle-qbank_genai#2]
Hello,
I want to report an issue with Namespace collisions.
All functions in lib.php should be prefixed with your plugin name.

Please review more documentation:
https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions
https://moodledev.io/general/development/policies/codingstyle#functions-and-methods

**Comment by mudrd8mz** [comment]
+1 this is critical - all lib.php from all plugins are loaded by Moodle core into the global scope. There is a big potential for collision.
