### ISSUE TITLE
Missed Privacy API implementation

### ISSUE THREAD

**Issue by volodymyrdovhan** [cgrevisse/moodle-qbank_genai#3]
Hello,

your plugin does not store personal information in DB and it sends just resource files content to OpenAI. But you still need to implement the Privacy API class and let Moodle know about your plugin.

More details:
https://moodledev.io/general/community/plugincontribution/checklist#privacy

Note: you can review other qbank plugins and how the Privacy API is implemented. For example, qbank_viewquestiontext or qbank_deletequestion.

**Comment by mudrd8mz** [comment]
+1 - valid privacy API implementation is required for all plugins that integrate with an external system. Good catch!

**Comment by cgrevisse** [comment]
Hi @volodymyrdovhan and @mudrd8mz ,

Thank you for your feedback.

In this case, as no personal information is stored and only the content of resources files is sent to OpenAI, would a `null_provider` like in the two plugins you mentioned be the appropriate choice?
