### ISSUE TITLE
Wrong files copying in moodledata

### ISSUE THREAD

**Issue by volodymyrdovhan** [cgrevisse/moodle-qbank_genai#4]
Hello,

In '/classes/task/generation_task.php' you are copying the existing file to the new file with an extension in the same filed folder.
![image](https://github.com/user-attachments/assets/89604de3-3b25-44a9-aa9f-78db42e93e8e)

Moodle prevents direct access to the files and all operations with files should be implemented with File Storage API.
You can use existing functions to copy local files: https://moodledev.io/docs/4.5/apis/subsystems/files#copy-a-file-in-the-file-storage-api-to-elsewhere-on-disk

Thanks

**Comment by mudrd8mz** [comment]
+1 this is a serious infiltration into the Moodle files API internals
